name: 'Deploy Previews to Cloud'

on:
  push:
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: '/ux-research/dist/'
          build_command: 'npm run build:ux-research'
